### PR TITLE
[DONOTMERGE]  swc sourcemap

### PR DESCRIPTION
**Pull request by RiESAEX**
https://github.com/swc-project/swc/issues/4112
I'm not sure what problem you are meeting, 
so I create a fork to show what I did.

### CODE REVIEW

**Comment by djalbat** [comment]
Many thanks I'll take a look later!

**Comment by djalbat** [comment]
I took a look at the fork, thank you. As I pointed out, however, the original source file is not included in the source map in `preambe.js` this time around and therefore I cannot check the mappings in the source map visualiser.

I ran `swc` myself yesterday and the original source *was* included so I am wondering what has changed in a meantime. What versions were you using yesterday?

**Comment by RiESAEX** [comment]
@swc/cli: 0.1.56
@swc/core: 1.2.160

**Comment by djalbat** [comment]
Yeah, so much about all this just confuses me. 

I have added further comments (and deleted one or two!) from the original issue now.

One thing, though... 

From your branch I see that the original source is not being included in the source maps when you run `swc`, so how were you able to check the source map in the visualiser at all?

If we could run `swc` standalone to get a source map that works and that has the source content included then that would be a good place to be.

**Comment by RiESAEX** [comment]
just upload it in custom button.
```
> atob('eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIi4uLy4uL3NyYy9leGFtcGxlL3ByZWFtYmxlLmpzIl0sInNvdXJjZXNDb250ZW50IjpbIlwidXNlIHN0cmljdFwiO1xuXG5pbXBvcnQgeyBSZWFjdCwgd2luZG93IH0gZnJvbSBcImVhc3lcIjtcblxud2luZG93LmFzc2lnbih7XG4gIFJlYWN0XG59KTtcbiJdLCJuYW1lcyI6WyJ3aW5kb3ciLCJhc3NpZ24iLCJSZWFjdCJdLCJtYXBwaW5ncyI6IkFBQUEsWUFBWSxDQUFDO0FBRWlCLElBQUEsS0FBTSxXQUFOLE1BQU0sQ0FBQTtBQUVwQ0EsS0FBTSxRQUFDQyxNQUFNLENBQUM7SUFKZCxBQUtFQyxLQUFLLEVBQUxBLEtBQUssTUFBTEE7Q0FDRCxDQUFDLENBQUMifQ==')
'{"version":3,"sources":["../../src/example/preamble.js"],"sourcesContent":["\\"use strict\\";\\n\\nimport { React, window } from \\"easy\\";\\n\\nwindow.assign({\\n  React\\n});\\n"],"names":["window","assign","React"],"mappings":"AAAA,YAAY,CAAC;AAEiB,IAAA,KAAM,WAAN,MAAM,CAAA;AAEpCA,KAAM,QAACC,MAAM,CAAC;IAJd,AAKEC,KAAK,EAALA,KAAK,MAALA;CACD,CAAC,CAAC"}'
```

**Comment by djalbat** [comment]
Thank you. It's copied here for future reference:

```
eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIi4uLy4uL3NyYy9leGFtcGxlL3ByZWFtYmxlLmpzIl0sInNvdXJjZXNDb250ZW50IjpbIlwidXNlIHN0cmljdFwiO1xuXG5pbXBvcnQgeyBSZWFjdCwgd2luZG93IH0gZnJvbSBcImVhc3lcIjtcblxud2luZG93LmFzc2lnbih7XG4gIFJlYWN0XG59KTtcbiJdLCJuYW1lcyI6WyJ3aW5kb3ciLCJhc3NpZ24iLCJSZWFjdCJdLCJtYXBwaW5ncyI6IkFBQUEsWUFBWSxDQUFDO0FBRWlCLElBQUEsS0FBTSxXQUFOLE1BQU0sQ0FBQTtBQUVwQ0EsS0FBTSxRQUFDQyxNQUFNLENBQUM7SUFKZCxBQUtFQyxLQUFLLEVBQUxBLEtBQUssTUFBTEE7Q0FDRCxDQUFDLENBQUMifQ==
```
And the formatted JSON:
```
{
   "version":3,
   "sources":[
      "../../src/example/preamble.js"
   ],
   "sourcesContent":[
      "\"use strict\";\n\nimport { React, window } from \"easy\";\n\nwindow.assign({\n  React\n});\n"
   ],
   "names":[
      "window",
      "assign",
      "React"
   ],
   "mappings":"AAAA,YAAY,CAAC;AAEiB,IAAA,KAAM,WAAN,MAAM,CAAA;AAEpCA,KAAM,QAACC,MAAM,CAAC;IAJd,AAKEC,KAAK,EAALA,KAAK,MAALA;CACD,CAAC,CAAC"
}
```

**Comment by djalbat** [comment]
Can you confirm that you generated this with `swc ./src -d ./lib -s inline`?

**Comment by RiESAEX** [comment]
yes 
`npm run swc` and `npx swc ./src -d ./lib -s inline` both output this

**Comment by djalbat** [comment]
I've added `preamble.working.js` and `preamble.broken.js` to the root of this repository. They differ, so I'm going to try to figure out where the problem lies.

**Comment by djalbat** [comment]
Here is the working source map:
```
{
  "version":3,
  "sources":[
    "../../src/example/preamble.js"
  ],
  "sourcesContent":[
    "\"use strict\";\n\nimport { React, window } from \"easy\";\n\nwindow.assign({\n  React\n});\n"
  ],
  "names":[
    "window",
    "assign",
    "React"
  ],
  "mappings":"AAAA,YAAY,CAAC;AAEiB,IAAA,KAAM,WAAN,MAAM,CAAA;AAEpCA,KAAM,QAACC,MAAM,CAAC;IAJd,AAKEC,KAAK,EAALA,KAAK,MAALA;CACD,CAAC,CAAC"
}
```
And here is the broken source map:
```
{
  "version":3,
  "sources":[
    "../../src/example/preamble.js"
  ],
  "sourcesContent":[
    "\"use strict\";\n\nimport { React, window } from \"easy\";\n\nwindow.assign({\n  React\n});\n"
  ],
  "names":[
    "window",
    "assign",
    "React"
  ],
  "mappings":"AAAA,YAAY,CAAC;AAEiB,IAAA,KAAM,WAAN,MAAM,CAA
<img width="1457" alt="Screenshot 2022-03-25 at 15 05 17" src="https://user-images.githubusercontent.com/17334729/160147100-4f18a90b-6b12-431a-b2a3-03322003569b.png">
A;AAEpCA,KAAM,QAACC,MAAM,CAAC;ICJd,ADKEC,KAAK,EAALA,KAAK,MAALA;CACD,CAAC,CAAC"
}
```
As expected, the only difference between the two is about three quarters of the way along the mappings, see attached.

**Comment by djalbat** [comment]
I've added three further files to the root:

* `preamble.working.js`
* `preamble.broken.js`
*  `preambe.intermediate.js`

The first two are those referenced above whilst the third is produced by SWC when called from Watchful. The *last* two are essentially identical, that is, the output from SWC when called from Watchful is broken.

Here is a scrreen shot of the output from the debugger:

Screenshot 2022-03-25 at 15 15 09

You can clearly see, about three quarters of the way along, the tell-tale `ICJd,ADKEC` values, which are the ones that are causing the problem.

Thus, for some reason, SWC is outputting faulty source maps when called via Watchful.

**Comment by djalbat** [comment]
Please see my comment here:

https://github.com/swc-project/swc/issues/4112#issuecomment-1079137578

**Comment by RiESAEX** [comment]
I tried @swc/core 1.2.161 and looks like everything works fine.

**Comment by djalbat** [comment]
Yes, thank you so much. I really appreciate your efforts.

**Pull request closed without merging**
